name: Check syntax and docs
on:
  - pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v0.6.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x
          terraform_wrapper: false

      - name: Run tf Tests
        working-directory: example
        run: |
          terraform init
          terraform validate
